import type { Proyecto } from '../interfaces/interfaces';

 export const ProyectosCartas: Proyecto[] = [
    {
    titulo: 'SharkCat',
    tituloEn: 'SharkCat',
    descripcion: 'WebApp orientada a los microservicios, en el área academico',
    descripcionEn: 'WebApp oriented to microservices, in the academic area',
    herramientas: 'Next.js, NestJs, TypeScript, MySQL, AWS, Railway, Prisma, TailwindCSS',
    imagenUrl: '/imagenes/ImagenesPrincipales/SharkCat.jpg', 
    slug: 'sharkcat',
    slugEn: 'sharkcat',
    },
    {
    titulo: 'Red Neuronal Artificial',
    tituloEn:'Artificial Neural Network',
    descripcion: 'Entrenamien to y aplicación de dos redes neuronales artificiales para el reconocimiento facial y de  emociones.',
    descripcionEn: 'Training and application of two artificial neural networks for facial and emotion recognition.',
    herramientas: 'Phyton, TensorFlow, Keras, OpenCV',
    imagenUrl: '/imagenes/ImagenesPrincipales/ReconocimientoFAcial.jpg',
    slug: 'inteligencia',
    slugEn: 'artificial',
    },
    {
    titulo: 'Analista de datos',
    tituloEn:'Data Analyst',
    descripcion: 'Desarrollo de un aplicativo web, para un ETL, y usando Tableau para la visualización de datos.',
    descripcionEn:'Development of a web application for an ETL, and using Tableau for data visualization.',
    herramientas: 'Node.js, Express, Oracle, SqlServer, Tableau',
    imagenUrl: '/imagenes/ImagenesPrincipales/DataAnalist.jpg',
    slug: 'analista',
    slugEn: 'analista',
    },
    {
    titulo: 'Colegio de Contadores Hondureños',
    tituloEn: 'Colegio de Contadores Hondureños',
    descripcion: 'Se desarrolló el analisis y diseño del sistema de enseñanza para el colegio de contadores hondureños',
    descripcionEn:'The analysis and design of the teaching system for the Honduran accountants college was developed',
    herramientas: 'Figma, Excel, Word',
    imagenUrl: '/imagenes/ImagenesPrincipales/ColegioContadores.png',
    slug: 'colegio',
    slugEn: 'colegio',
    },
    {
    titulo: 'Inversiones Cacéres',
    tituloEn: 'Inversiones Cacéres',
    descripcion: 'Análisis de vibilidad de un sistema de gestión de inventario, a través de sistemas de información existentes',
    descripcionEn:'Visibility analysis of an inventory management system, through existing information systems',
    herramientas: 'PostgresSql, Odoo,Figma',
    imagenUrl: '/imagenes/ImagenesPrincipales/Inversiones caceres.png',
    slug: 'inversiones',
    slugEn: 'inversiones',
    },
    {
    titulo: 'SwiftDrop',
    tituloEn:'SwiftDrop',
    descripcion: 'Una aplicación móvil para la gestión de delivery',
    descripcionEn: 'A mobile application for delivery management',
    herramientas: 'Node.js, express, MongoDB, TypeScript',
    imagenUrl: '/imagenes/ImagenesPrincipales/swiftDrop.png',
    slug: 'swiftdrop',
    slugEn: 'swiftdrop',
    },
    {
    titulo: 'Infraestructura con Azure y Terraform',
    tituloEn:'Infrastructure with Azure and Terraform',
    descripcion: 'Infraestructura como código, para la creación de una infraestructura en Azure, usando Terraform',
    descripcionEn:'Infrastructure as code, for the creation of infrastructure in Azure, using Terraform',
    herramientas: 'Azure, Terraform, Docker',
    imagenUrl: '/imagenes/terraform.png',
    slug: 'terraform',
    slugEn: 'terraform',
    },
    {
    titulo: 'Servicios en la nube con PokeApi',
    tituloEn: 'Cloud Services with PokeApi',
    descripcion: 'Desarrollo de un sistema para obtener información de pokemones, usando la PokeApi y con servicios en la nube',
    descripcionEn: 'Development of a system to obtain information about pokemons, using the PokeApi and with cloud services',
    herramientas: 'Terraform, Azure, Docker, Next.js, SQL, FastAPI',
    imagenUrl: '/imagenes/ImagenesPrincipales/pokeapi.png',
    slug: 'pokeapi',
    slugEn: 'pokeapi',
    },
    
];

